Repository RoboticSpaceExploration/protobot, pull requests merged in 2021-11, with the labels that each got.

#7 Deleted unnecessary files
  src/protobot_bringup/launch/launch.log
  src/protobot_description/launch/frames.gv
  src/protobot_description/launch/frames.pdf
  src/protobot_description/urdf/frames.gv
  src/protobot_description/urdf/frames.pdf
  src/protobot_localization/launch/frames.gv
  src/protobot_localization/launch/frames.pdf
Labels: cleanup/refactoring, autonomy

#8 Deleted launch prefix for protobot_teleop launch file
  src/protobot_teleop/launch/protobot_teleop.launch
Labels: bug, autonomy

#11 Issue05
  .gitmodules
  src/protobot_bringup/launch/protobot_core.launch
  src/protobot_mapping/CMakeLists.txt
  src/protobot_mapping/launch/OdometryTransform.launch
  src/protobot_mapping/launch/protobot_mapping.launch
  src/protobot_mapping/package.xml
  src/protobot_mapping/src/OdometryTransform.cpp
Labels: feature, autonomy
